plugins { id 'com.android.application' }
android {
    namespace 'com.wobuxian.game'
    compileSdk 35
    buildToolsVersion '35.0.0'
    defaultConfig {
        applicationId 'com.wobuxian.game'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }
    buildTypes {
        debug { minifyEnabled false }
        release { minifyEnabled false; signingConfig signingConfigs.debug }
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    aaptOptions { noCompress 'html','js','css' }
}
